function com_liu_trymylanguage_TryMyLanguageJUnit(){var N='',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',gb='"><\/script>',X='#',Ub='.cache.html',Z='/',Tb=':',mb='::',gc='<script defer="defer">com_liu_trymylanguage_TryMyLanguageJUnit.onInjectionDone(\'com.liu.trymylanguage.TryMyLanguageJUnit\')<\/script>',fb='<script id="',cc='<script language="javascript" src="',pb='=',Y='?',Fb='ActiveXObject',rb='Bad handler "',Gb='ChromeTab.ChromeFrame',ac='DOMContentLoaded',Ab='EventSource',Sb="GWT module 'com.liu.trymylanguage.TryMyLanguageJUnit' may need to be (re)compiled",hb='SCRIPT',eb='__gwt_marker_com.liu.trymylanguage.TryMyLanguageJUnit',ib='base',ab='baseUrl',R='begin',Q='bootstrap',Eb='chromeframe',_='clear.cache.gif',O='com.liu.trymylanguage.TryMyLanguageJUnit',cb='com.liu.trymylanguage.TryMyLanguageJUnit.nocache.js',lb='com.liu.trymylanguage.TryMyLanguageJUnit::',ob='content',W='end',zb='event.source',Mb='gecko',Nb='gecko1_8',S='gwt.codesvr=',T='gwt.hosted=',U='gwt.hybrid',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',$b='head',Qb='hosted.html?com_liu_trymylanguage_TryMyLanguageJUnit',Zb='href',Lb='ie6',Kb='ie8',Jb='ie9',vb='iframe',$='img',wb="javascript:''",_b='lib/codemirror.css',bc='lib/codemirror.js',dc='lib/codemirror.js"><\/script>',Wb='link',Pb='loadExternalRefs',jb='meta',ec='mode/basemode.js',fc='mode/basemode.js"><\/script>',yb='moduleRequested',V='moduleStartup',Ib='msie',kb='name',Cb='opera',xb='position:absolute;width:0;height:0;border:none',Xb='rel',Hb='safari',bb='script',Rb='selectingPermutation',P='startup',Yb='stylesheet',Vb='theme/default.css',db='undefined',Ob='unknown',Bb='user.agent',Db='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=N,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:R});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(S)!=-1||(c.indexOf(T)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(U)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(O);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return F(a)}}com_liu_trymylanguage_TryMyLanguageJUnit=null;c.gwtOnLoad(y,O,s,x);n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:V,millis:(new Date).getTime(),type:W})}}
function C(){function e(a){var b=a.lastIndexOf(X);if(b==-1){b=a.length}var c=a.indexOf(Y);if(c==-1){c=a.length}var d=a.lastIndexOf(Z,Math.min(c,b));return d>=0?a.substring(0,d+1):N}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement($);b.src=a+_;a=e(b.src)}return a}
function g(){var a=E(ab);if(a!=null){return a}return N}
function h(){var a=m.getElementsByTagName(bb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(cb)!=-1){return e(a[b].src)}}return N}
function i(){var a;if(typeof isBodyLoaded==db||!isBodyLoaded()){var b=eb;var c;m.write(fb+b+gb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=hb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return N}
function j(){var a=m.getElementsByTagName(ib);if(a.length>0){return a[a.length-1].href}return N}
var k=g();if(k==N){k=h()}if(k==N){k=i()}if(k==N){k=j()}if(k==N){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(jb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(kb),g;if(f){f=f.replace(lb,N);if(f.indexOf(mb)>=0){continue}if(f==nb){g=e.getAttribute(ob);if(g){var h,i=g.indexOf(pb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=N}t[f]=h}}else if(f==qb){g=e.getAttribute(ob);if(g){try{z=eval(g)}catch(a){alert(rb+g+sb)}}}else if(f==tb){g=e.getAttribute(ob);if(g){try{y=eval(g)}catch(a){alert(rb+g+ub)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var G;function H(){if(!G){G=true;var a=m.createElement(vb);a.src=wb;a.id=O;a.style.cssText=xb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:V,millis:(new Date).getTime(),type:yb});a.contentWindow.location.replace(s+J)}}
v[zb]=function(){return Ab in window};u[zb]={'false':0,'true':1};v[Bb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Cb)!=-1}())return Cb;if(function(){return c.indexOf(Db)!=-1||function(){if(c.indexOf(Eb)!=-1){return true}if(typeof window[Fb]!=db){try{var b=new ActiveXObject(Gb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Hb;if(function(){return c.indexOf(Ib)!=-1&&m.documentMode>=9}())return Jb;if(function(){return c.indexOf(Ib)!=-1&&m.documentMode>=8}())return Kb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Lb;if(function(){return c.indexOf(Mb)!=-1}())return Nb;return Ob};u[Bb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};com_liu_trymylanguage_TryMyLanguageJUnit.onScriptLoad=function(){if(G){q=true;B()}};com_liu_trymylanguage_TryMyLanguageJUnit.onInjectionDone=function(){p=true;n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Pb,millis:(new Date).getTime(),type:W});B()};D();C();var I;var J;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(O))){l.location.reload();return}J=Qb;I=N}n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:Rb});if(!A()){try{alert(Sb);return;var K=I.indexOf(Tb);if(K!=-1){x=Number(I.substring(K+1));I=I.substring(0,K)}J=I+Ub}catch(a){return}}var L;function M(){if(!r){r=true;if(!__gwt_stylesLoaded[Vb]){var a=m.createElement(Wb);__gwt_stylesLoaded[Vb]=a;a.setAttribute(Xb,Yb);a.setAttribute(Zb,s+Vb);m.getElementsByTagName($b)[0].appendChild(a)}if(!__gwt_stylesLoaded[_b]){var a=m.createElement(Wb);__gwt_stylesLoaded[_b]=a;a.setAttribute(Xb,Yb);a.setAttribute(Zb,s+_b);m.getElementsByTagName($b)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(ac,M,false)}if(L){clearInterval(L)}}}
if(m.addEventListener){m.addEventListener(ac,function(){H();M()},false)}var L=setInterval(function(){if(/loaded|complete/.test(m.readyState)){H();M()}},50);n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:W});n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Pb,millis:(new Date).getTime(),type:R});if(!__gwt_scriptsLoaded[bc]){__gwt_scriptsLoaded[bc]=true;document.write(cc+s+dc)}if(!__gwt_scriptsLoaded[ec]){__gwt_scriptsLoaded[ec]=true;document.write(cc+s+fc)}m.write(gc)}
com_liu_trymylanguage_TryMyLanguageJUnit();